// react-near/src/App.jsx
import React, { useState, useEffect, useCallback } from 'react';
import { setupWalletSelector } from '@near-wallet-selector/core';
import { setupModal } from '@near-wallet-selector/modal-ui';
import { setupMyNearWallet } from '@near-wallet-selector/my-near-wallet';
import { setupHereWallet } from '@near-wallet-selector/here-wallet';
import '@near-wallet-selector/modal-ui/styles.css';

const CONTRACT_ID = 'guest-book.testnet';
const NETWORK = 'testnet';

export default function App() {
  const [selector, setSelector] = useState(null);
  const [modal, setModal] = useState(null);
  const [accountId, setAccountId] = useState(null);
  const [greeting, setGreeting] = useState('');

  useEffect(() => {
    setupWalletSelector({
      network: NETWORK,
      modules: [setupMyNearWallet(), setupHereWallet()],
    }).then((sel) => {
      setSelector(sel);
      const m = setupModal(sel, { contractId: CONTRACT_ID });
      setModal(m);
      const state = sel.store.getState();
      if (state.accounts.length > 0) {
        setAccountId(state.accounts[0].accountId);
      }
      sel.store.observable.subscribe((state) => {
        const acct = state.accounts.find((a) => a.active);
        setAccountId(acct ? acct.accountId : null);
      });
    });
  }, []);

  const handleSignIn = () => modal && modal.show();

  const handleSignOut = async () => {
    if (!selector) return;
    const wallet = await selector.wallet();
    await wallet.signOut();
    setAccountId(null);
  };

  const callContract = useCallback(async () => {
    if (!selector) return;
    const wallet = await selector.wallet();
    try {
      const result = await wallet.signAndSendTransaction({
        receiverId: CONTRACT_ID,
        actions: [{
          type: 'FunctionCall',
          params: {
            methodName: 'getGreeting',
            args: {},
            gas: '30000000000000',
            deposit: '0',
          },
        }],
      });
      setGreeting(JSON.stringify(result, null, 2));
    } catch (e) {
      setGreeting('Error: ' + e.message);
    }
  }, [selector]);

  return (
    <div style={{ maxWidth: 600, margin: '40px auto', fontFamily: 'sans-serif' }}>
      <h1>React + NEAR Starter</h1>
      <p>Network: {NETWORK} | Contract: {CONTRACT_ID}</p>
      {accountId ? (
        <>
          <p>Connected: <strong>{accountId}</strong></p>
          <button onClick={callContract}>Call Contract</button>
          <button onClick={handleSignOut} style={{ marginLeft: 8 }}>Sign Out</button>
          {greeting && <pre style={{ background: '#f5f5f5', padding: 12 }}>{greeting}</pre>}
        </>
      ) : (
        <button onClick={handleSignIn}>Connect NEAR Wallet</button>
      )}
    </div>
  );
}

// svelte-near/src/App.svelte
<script>
  import { onMount } from 'svelte';
  import { setupWalletSelector } from '@near-wallet-selector/core';
  import { setupModal } from '@near-wallet-selector/modal-ui';
  import { setupMyNearWallet } from '@near-wallet-selector/my-near-wallet';
  import { setupHereWallet } from '@near-wallet-selector/here-wallet';
  import '@near-wallet-selector/modal-ui/styles.css';

  const CONTRACT_ID = 'guest-book.testnet';
  const NETWORK = 'testnet';

  let selector = null;
  let modal = null;
  let accountId = null;
  let result = '';

  onMount(async () => {
    selector = await setupWalletSelector({
      network: NETWORK,
      modules: [setupMyNearWallet(), setupHereWallet()],
    });
    modal = setupModal(selector, { contractId: CONTRACT_ID });
    const state = selector.store.getState();
    if (state.accounts.length > 0) accountId = state.accounts[0].accountId;
    selector.store.observable.subscribe((s) => {
      const acct = s.accounts.find((a) => a.active);
      accountId = acct ? acct.accountId : null;
    });
  });

  function signIn() { modal?.show(); }

  async function signOut() {
    const wallet = await selector.wallet();
    await wallet.signOut();
    accountId = null;
  }

  async function callContract() {
    try {
      const wallet = await selector.wallet();
      const res = await wallet.signAndSendTransaction({
        receiverId: CONTRACT_ID,
        actions: [{
          type: 'FunctionCall',
          params: { methodName: 'getGreeting', args: {}, gas: '30000000000000', deposit: '0' },
        }],
      });
      result = JSON.stringify(res, null, 2);
    } catch (e) { result = 'Error: ' + e.message; }
  }
</script>

<div style="max-width: 600px; margin: 40px auto; font-family: sans-serif">
  <h1>Svelte + NEAR Starter</h1>
  <p>Network: {NETWORK} | Contract: {CONTRACT_ID}</p>
  {#if accountId}
    <p>Connected: <strong>{accountId}</strong></p>
    <button on:click={callContract}>Call Contract</button>
    <button on:click={signOut} style="margin-left: 8px">Sign Out</button>
    {#if result}<pre style="background: #f5f5f5; padding: 12px">{result}</pre>{/if}
  {:else}
    <button on:click={signIn}>Connect NEAR Wallet</button>
  {/if}
</div>
